flaskr/routes.py
import atexit, threading, time, string
from flask import current_app as app

from flask import Blueprint, render_template, redirect, url_for, flash, request, copy_current_request_context
from flask_login import current_user, login_user, logout_user, login_required

from flaskr.forms import LoginForm
from flaskr.models import db, User, Setup, GpsData
from flaskr.rover import Rover as rover
from flaskr import rover_controller, gps_controller

checkConnectionDaemonStopEvent = threading.Event()
GPSDaemonStopEvent = threading.Event()
isCheckConnectionDaemonStarted = False
isGPSDaemonStarted = False

checkConnectionDaemon = threading.Thread()
GPSDaemon = threading.Thread()

view = Blueprint("view", __name__)

rover_controller.gpioSetup()

@view.route("/clientConnected", methods=["GET", "POST"])
# end-point called by js post client
def clientConntected():
    if current_user.is_authenticated:
        setup = Setup.query.filter_by(id=1).first()
        clientConnected = request.form.get('clientConnected')
        if clientConnected == 'True' :
            log('Client status: connected (keep-alive received every {0}s.)'.format(setup.client_keepalive_interval))
            rover_controller.rover.clientConnected = True
        return render_template("homepage.html", user=current_user, setup=setup, rover_controller=rover_controller, gps_controller=gps_controller)

    return redirect(url_for('view.login'))

@view.route("/", methods=["GET", "POST"])
def homepage():
    if current_user.is_authenticated:
        setup = Setup.query.filter_by(id=1).first()
        startCheckConnectionDaemon()
        startGPSDaemon()
        commandRequest = request.form.get('command')
        if commandRequest != None :
            rover_controller.execute_command('CHANGE_STATUS', commandRequest)
        powerSlider = request.form.get('powerSlider')
        if powerSlider != None :
            rover_controller.execute_command('CHANGE_POWER', powerSlider)
        return render_template("homepage.html", user=current_user, setup=setup, rover_controller=rover_controller, gps_controller=gps_controller)

    return redirect(url_for('view.login'))

@view.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('view.homepage'))
    
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            msg = "Invalid credentials"
            flash(msg, category='warning')
            return redirect(url_for('view.login'))
        elif user.enabled == 0:
            msg = "User disabled"
            flash(msg, category='warning')
            return redirect(url_for('view.login'))
        
        login_user(user, remember=form.remember_me.data)
        return redirect(url_for('view.homepage'))
    
    return render_template("login.html", form=form)

@view.route("/logout")
def logout():
    logout_user()
    cleanUp()
    return redirect(url_for('view.login'))

@view.route("/users")
@login_required
def users():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")

    users = User.query.all()
    return render_template("users.html", users=users)

@view.route("/setup")
@login_required
def setup():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")

    setup = Setup.query.filter_by(id=1).first()
    return render_template("setup.html", setup=setup)

@view.route("/new")
@login_required
def new():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")

    return render_template('new.html')

@view.route("/edit/<int:id>")
@login_required
def edit(id):
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")

    user = User.query.filter_by(id=id).first()
    return render_template("edit.html", user=user)

@view.route("/remove/<int:id>")
@login_required
def remove(id):
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")

    user = User.query.filter_by(id=id).first()
    return render_template("remove.html", user=user)

@view.route("/add_user", methods=["POST"])
@login_required
def add_user():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")
    try:
        username = request.form.get("username")        
        password = request.form.get("password")
        role = request.form.get("role")
        email = request.form.get("email")
        enabled = request.form.get("enabled")
        user = User(username=username)
        user.set_password_hash(password)
        user.role = role
        user.email = email
        user.enabled = 0
        if enabled == 'on':
            user.enabled = 1
        db.session.add(user)
        db.session.commit()
    except Exception:
        msg = "Failed to add user {0}".format(username)
        flash(msg, category='danger')
        return redirect("/new")

    return redirect("/users")

@view.route("/update_user", methods=["POST"])
@login_required
def update_user():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")
    try:
        newUsername = request.form.get("newUsername")
        oldUsername = request.form.get("oldUsername")
        password = request.form.get("password")
        oldPassword = request.form.get("oldPassword")
        role = request.form.get("role")
        email = request.form.get("email")
        enabled = request.form.get("enabled")
        user = User.query.filter_by(username=oldUsername).first()
        user.username = newUsername
        if oldPassword != password:
            user.set_password_hash(password)
        user.role = role
        user.email = email
        user.enabled = 0
        if enabled == 'on':
            user.enabled = 1
        db.session.commit()
    except Exception:
        msg = "Failed to update user {0}".format(oldUsername)
        flash(msg, category='danger')
        return redirect("/edit")

    return redirect("/users")

@view.route("/delete", methods=["POST"])
@login_required
def delete():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")
    try:
        username = request.form.get("username")
        user = User.query.filter_by(username=username).first()
        db.session.delete(user)
        db.session.commit()
    except Exception:
        msg = "Failed to delete user {0}".format(username)
        flash(msg, category='danger')

    return redirect("/users")

@view.route("/save_setup", methods=["POST"])
@login_required
def save_setup():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")
    try:
        camera_ip = request.form.get("camera_ip")
        gps_interval = request.form.get("gps_interval")
        url_geomap = request.form.get("url_geomap")
        gps_store = request.form.get("gps_store")
        stop_on_lost_connection_interval = request.form.get("stop_on_lost_connection_interval")
        client_keepalive_interval = request.form.get("client_keepalive_interval")

        setup = Setup.query.filter_by(id=1).first()
        setup.camera_ip = camera_ip
        setup.gps_interval = int(gps_interval)
        setup.gps_store = int(gps_store)
        setup.url_geomap = url_geomap
        setup.stop_on_lost_connection_interval = int(stop_on_lost_connection_interval)
        setup.client_keepalive_interval = int(client_keepalive_interval)

        db.session.commit()
        msg = "Setup successfully saved"
        flash(msg, category='info')
    except Exception:
        msg = "Failed to save setup"
        flash(msg, category='danger')

    return redirect("/setup")

@view.route("/gpsdatalist")
@login_required
def gpsdatalist():
    if not current_user.role == 'ADMIN':
        return render_template("homepage.html")

    gpsdatalist = GpsData.query.all()
    return render_template("gpsdatalist.html", gpsdatalist=gpsdatalist)

@view.route("/deleteGpsData")
def deleteGpsData():
    try:
        db.session.query(GpsData).delete()
        db.session.commit()
        msg = "All GPS data successfully deleted"
        flash(msg, category='info')
    except Exception as e:
        msg = "Failed to delete GPS data"
        print(e)
        flash(msg, category='danger')
    return redirect("/gpsdatalist")

# Daemon to check client connection every 'interval' seconds, due to 'interval' setup value.
def startCheckConnectionDaemon():
    global isCheckConnectionDaemonStarted
    
    if isCheckConnectionDaemonStarted:
        return
    stop_on_lost_connection_interval = Setup.query.filter_by(id=1).first().stop_on_lost_connection_interval
    if stop_on_lost_connection_interval < 1:
        log('checkConnectionDaemon not startable due to interval value {0}s.'.format(stop_on_lost_connection_interval))
        return 

    @copy_current_request_context
    def checkConnectionDaemonProcess(name, checkConnectionDaemonStopEvent):
        while not checkConnectionDaemonStopEvent.is_set():
            stop_on_lost_connection_interval = Setup.query.filter_by(id=1).first().stop_on_lost_connection_interval
            log('checking client connection alive (every {0}s.)'.format(stop_on_lost_connection_interval))
            time.sleep(stop_on_lost_connection_interval)
            if not rover_controller.rover.clientConnected:
                log('client connection lost!')
                rover_controller.stopMotors()
            rover_controller.rover.clientConnected = False
    
    log('isCheckConnectionDaemonStarted: {0}'.format(isCheckConnectionDaemonStarted))

    if not isCheckConnectionDaemonStarted:
        checkConnectionDaemon.__init__(target=checkConnectionDaemonProcess, args=('CheckConnectionDaemon', checkConnectionDaemonStopEvent), daemon=True)
        checkConnectionDaemon.start()
        isCheckConnectionDaemonStarted = True

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/roverw.svg') }}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
        
    <!-- DARK MODE -->
    <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.css">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    
    <script src="{{ url_for('static', filename='js/init.js') }}"></script>

    <title>Dagu Rover</title>
</head>

<body">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">

        <a class="navbar-brand" href="{{ url_for('view.homepage') }}" data-toggle="tooltip" title="Home">
            <img src="{{ url_for('static', filename='img/roverb.png') }}" class="img-logo">
            {{ current_user.username }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>            

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                        {% if current_user.role == 'ADMIN' %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Settings
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-item nav-link" href="{{ url_for('view.users') }}" data-toggle="tooltip" title="Users">
                                        Users
                                    </a>
                                    <a class="nav-item nav-link" href="{{ url_for('view.gpsdatalist') }}" data-toggle="tooltip" title="GPS Data">
                                        GPS Data
                                    </a>
                                    <a class="nav-item nav-link" href="{{ url_for('view.setup') }}" data-toggle="tooltip" title="Setup">
                                        Setup
                                    </a>
                                </div>
                            </li>
                        {% endif %} 
                        <li class="nav-item active">
                        <a class="nav-item nav-link" onclick="stopKeepAlive();" href="{{ url_for('view.logout') }}" data-toggle="tooltip" title="Logout">
                            Logout
                        </a>
                        </li>
                    {% endif %}
                    </ul>
            </div>

    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

flaskr/templates/edit.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center mt-3">
    <div class="row no-gutters justify-content-center">
        <div class="col-md-4">

            <div class="container">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

            <form method="POST" action="/update_user">
                <div class="form-group">
                    <label for="newUsername">Username</label>
                    <input type="hidden" class="form-control" name="oldUsername" value="{{user.username}}" id="oldUsername" aria-describedby="oldUsername">
                    <input type="text" class="form-control" name="newUsername" value="{{user.username}}" id="newUsername" aria-describedby="newUsername" placeholder="Enter name" required="true" readonly="true">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" name="password" value="{{user.password}}" id="password" aria-describedby="password" placeholder="Enter password" required="true">
                    <input type="hidden" class="form-control" name="oldPassword" value="{{user.password}}" id="oldPassword" aria-describedby="oldPassword">

                    <label for="role">Role</label>
                    <select type="text" class="form-control" id="role" name="role" >
                        <option value="ADMIN" {% if user.role == 'ADMIN' %} selected {% endif %}>ADMIN</option>
                        <option value="USER" {% if user.role == 'USER' %} selected {% endif %}>USER</option>
                    </select>                
                    <label for="email">Email</label>
                    <input type="text" class="form-control" name="email" value="{{user.email}}" id="email" aria-describedby="email" placeholder="Enter email" required="true">
                </div>
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" name="enabled" id="enabled" {% if user.enabled == 1 %} checked {% endif %}>
                    <label class="custom-control-label" for="enabled">Enabled</label>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
                <a class="btn btn-primary" href="{{ url_for('view.users') }}" role="button">Back</a>
            </form>


        </div>
    </div>
</div>


{% endblock %}

flaskr/templates/gpsdatalist.html
{% extends 'base.html' %}

{% block content %}

<script>
    $(document).ready(function() {
        $('#gpsdatalist_table').DataTable( {
            dom: 'Bftipr',
            pageLength: 8,
            order: [[ 0, 'des' ]],
            buttons: [ 'csv', 'pdf', 'copy' ]
        });
    } );
</script>

<div class="container text-center mt-3">
    <div class="row no-gutters justify-content-center">
        <div class="col-md-4">

            <div class="container">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}" role="alert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

            <table id="gpsdatalist_table" class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Lat</th>
                        <th scope="col">Lon</th>
                        <th scope="col">Alt</th>
                        <th scope="col">Sat</th>
                    </tr>
                </thead>
                <tbody>
                {% for gpsdata in gpsdatalist %}
                    <tr>
                        <td><a href="{{gpsdata.url}}" target="_blank">{{gpsdata.id}}</a></td>
                        <td>{{gpsdata.latitude}}</td>
                        <td>{{gpsdata.longitude}}</td>
                        <td>{{gpsdata.altitude}}</td>
                        <td>{{gpsdata.satellites}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <div>
                <a class="btn btn-primary" href="{{ url_for('view.deleteGpsData') }}" role="button">Delete all</a>
                <a class="btn btn-primary" href="{{ url_for('view.gpsdatalist') }}" role="button">Refresh</a>
                <a class="btn btn-primary" href="{{ url_for('view.homepage') }}" role="button">Back</a>
            </div>

        </div>
    </div>
</div>

{% endblock %}

flaskr/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container text-center mt-3">
    <div class="row no-gutters justify-content-center">
        <div class="col-md-4">
            
            <div class="container">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}" role="alert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

            <form method="POST" novalidate>
                {{ form.hidden_tag() }} <!-- csrf_token -->
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username(class="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password(class="form-control") }}
                </div>
                <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
                {{ form.submit(class="btn btn-outline-secondary") }}
            </form>

        </div>
    </div> 
</div>
{% endblock %}

flaskr/templates/new.html
{% extends 'base.html' %}

{% block content %}

    <div class="container content-container">
        <div class="mt-3">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>
    </div>

    <div class="container content-container">
        <form method="POST" action="/add_user">
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" aria-describedby="username" placeholder="Enter name" required="true">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" aria-describedby="password" placeholder="Enter password" required="true">
                <label for="role">Role</label>
                <select class="form-control" id="role" name="role">
                    <option value="ADMIN">ADMIN</option>
                    <option value="USER" selected>USER</option>
                </select>                
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" id="email" aria-describedby="email" placeholder="Enter email" required="true">
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="enabled" id="enabled">
                <label class="custom-control-label" for="enabled">Enabled</label>
              </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-primary" href="{{ url_for('view.users') }}" role="button">Back</a>
        </form>
    </div>

{% endblock %}

flaskr/templates/remove.html
{% extends 'base.html' %}

{% block content %}

    <div class="container content-container">
        <div class="mt-3">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <p style="color: #dc3545">{{ message }}</p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <div class="container content-container">
        <form method="POST" action="/delete">
            <div class="form-group">
                <label for="username">Username</label>
                <input readonly type="text" class="form-control" value="{{user.username}}" name="username" id="username" aria-describedby="username" >
                <label for="role">Role</label>
                <input readonly type="text" class="form-control" value="{{user.role}}" name="role" id="role" aria-describedby="role">
                <label for="email">Email</label>
                <input readonly type="text" class="form-control" value="{{user.email}}" name="email" id="email" aria-describedby="email">
            </div>
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="enabled" id="enabled" {% if user.enabled == 1 %} checked {% endif %} disabled>
                <label class="custom-control-label" for="enabled">Enabled</label>
              </div>
            <button type="submit" class="btn btn-primary">Delete</button>
            <a class="btn btn-primary" href="{{ url_for('view.users') }}" role="button">Back</a>
        </form>
    </div>

{% endblock %}

flaskr/templates/setup.html
{% extends 'base.html' %}

{% block content %}

<div class="container text-center mt-3">
    <div class="row no-gutters justify-content-center">
        <div class="col-md-4">

            <div class="container">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}" role="alert">
                                <button type="button" class="close" data-dismiss="alert">&times;</button>
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

                <form method="POST" action="/save_setup">
                    <div class="form-group">
                        <label  for="camera_ip">Camera IP address</label>
                        <input type="text" name="camera_ip" class="form-control" id="camera_ip" value="{{ setup.camera_ip }}" placeholder="http://localhost:8081">
                        <label for="gps_interval">GPS interval (sec.) track (-1=no track)</label>
                        <input type="number" name="gps_interval" class="form-control" id="gps_interval" value="{{ setup.gps_interval }}" placeholder="GPS interval (s.)">
                        <label for="gps_store">Store GPS data limit (-1=no store) </label>
                        <input type="number" name="gps_store" class="form-control" id="gps_store" value="{{ setup.gps_store }}">
                        <label  for="url_geomap">URL to open geo coordinates</label>
                        <input type="text" name="url_geomap" class="form-control" id="url_geomap" value="{{ setup.url_geomap }}" placeholder="http://maps.google.com/maps?q={0},{1}">
                        <label for="client_keepalive_interval">Keep-alive from client (s.)</label>
                        <input type="number" name="client_keepalive_interval" class="form-control" id="client_keepalive_interval" value="{{ setup.client_keepalive_interval }}">
                        <label for="stop_on_lost_connection_interval">Stop on lost connection after (s.)</label>
                        <input type="number" name="stop_on_lost_connection_interval" class="form-control" id="stop_on_lost_connection_interval" value="{{ setup.stop_on_lost_connection_interval }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-primary" href="{{ url_for('view.homepage') }}" role="button">Back</a>
                </form>

        </div>

    </div>

{% endblock %}

flaskr/templates/users.html
{% extends 'base.html' %}

{% block content %}

<script>
    $(document).ready(function() {
        $('#user_table').DataTable( {
            "paging": true,
            "ordering": true,
            "info": false
        });
    } );
</script>

<div class="container text-center mt-3">
    <div class="row no-gutters justify-content-center">
        <div class="col-md-4">

            <div class="container">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <p style="color: #dc3545">{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>

            <table id="user_table" class="table table-sm">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Role</th>
                        <th scope="col">Email</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{user.username}}</td>
                        <td>{{user.role}}</td>
                        <td>{{user.email}}</td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownUserActions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Actions
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownUserActions">
                                    <a class="dropdown-item" href="{{ url_for('view.new') }}">New</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ url_for('view.edit', id=user.id) }}">Edit</a>
                                    <a class="dropdown-item" href="{{ url_for('view.remove', id=user.id) }}">Remove</a>
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <a class="btn btn-primary" href="{{ url_for('view.homepage') }}" role="button">Back</a>
        </div>
    </div>
</div>

{% endblock %}